### ISSUE TITLE
Error processing retroarch fbneo arcade only dat with igir-4.2.0-Linux-amd64.tar.gz

### ISSUE THREAD

**Issue by emerrepengo** [emmercm/igir#1836]
### Paste the command

```
./igir report --input "/mnt/NAS02/EMUS/roms/TEST/roms/" \
--dat "/mnt/NAS02/EMUS/roms/TEST/dats/FinalBurn Neo (ClrMame Pro XML, Arcade only)_last.dat" \
--report-output "/mnt/NAS02/EMUS/roms/TEST/igir_%YYYY-%MM-%DDT%HH:%mm:%ss.csv"
```

### Describe the bug

Using the report command with the last RetroArch FBNeo arcade data and the Linux amd64 binary ends with an "ERROR: Typethis.manufacturer?.toLowerCase is not a function" error and the report is never created.

### Expected behavior

Igir should generate a csv report in the "--report-output" defined path using the contents from the "--input" and "--dat" parameters.

### Debug logs

[igir_420-ra-fbneo-new_clean.log](https://github.com/user-attachments/files/21967540/igir_420-ra-fbneo-new_clean.log)

### DAT(s) used

https://github.com/libretro/FBNeo/blob/master/dats/FinalBurn%20Neo%20(ClrMame%20Pro%20XML%2C%20Arcade%20only).dat

### igir version

4.2.0

### Node.js version

N/A

### Operating system

Manjaro Linux

### Additional context

The issue seems to be related to the 4.x complied binaries and something in the .dat syntax. I'm able to reproduce the issue with 4.0.2 but it works with 3.4.2 binary and npx igir@latest version.

I did some tests with an older version of the .dat [07/07/2023](https://github.com/libretro/FBNeo/blob/f6979894588ce3b81773ccd0fcaf08362c277044/dats/FinalBurn%20Neo%20(ClrMame%20Pro%20XML%2C%20Arcade%20only).dat) and it fails too.

A much older version of the .dat [24/05/2020](https://github.com/libretro/FBNeo/blob/110fd1b58d55b9c2cfdc6e33e347587aee042066/dats/FinalBurn%20Neo%20(ClrMame%20Pro%20XML%2C%20Arcade%20only).dat) works.

**Comment by emerrepengo** [comment]
Other commands, like "fixdat", and other .dat from RA FinalBurn Neo (e. g. FinalBurn Neo (ClrMame Pro XML, Neogeo only).dat) throw the same error.

**Comment by emmercm** [comment]
https://github.com/emmercm/igir/issues/1900 is probably a duplicate of this issue, but it has more commenters & watchers.

Is this still a problem with the latest version of Igir?

**Comment by emerrepengo** [comment]
Not anymore. It works as expected with 4.3.1 compiled binary.

`
[mrpengo@desk igir]$ ./igir report --input "/mnt/NAS02/Public/EMUS/roms/zzz-TEST/roms/" \
--dat "/mnt/NAS02/Public/EMUS/roms/zzz-TEST/dats/FinalBurn Neo (ClrMame Pro XML, Arcade only)_last.dat" \
--report-output "/mnt/NAS02/Public/EMUS/roms/zzz-TEST/igir_%YYYY-%MM-%DDT%HH:%mm:%ss.csv"

   @@@@@@   @@@@@@     @@@@@@    @@@@@@@@
 @@      @@  @@      @@      @@         @@
 @@      @@  @@      @@      @@         @@   ROM collection manager
   @@@@@@   @@         @@@@@@   @@@@@@@@@    https://igir.io/
          @@@     @@@@        @@@
     @@   @@        @@   @@   @@       @@    v4.3.1
     @@   @@        @@   @@   @@       @@
     @@   @@@@@@@@@@@@   @@   @@       @@

 ✓ Parsing DATs » 1 DAT found
 ✓ Scanning for ROMs » 49 files found
 ✓ FinalBurn Neo - Arcade Games » 2/8025 games, 1/13 BIOSes, 2/6361 retail releases found
 ✓ Generating report » /mnt/NAS02/Public/EMUS/roms/zzz-TEST/igir_2026-02-23T14;28;31.csv
`

**Comment by emmercm** [comment]
Awesome, thank you!
